## Reading data from objects

In [1]:
import numpy as np
import xarray as xr

import earthkit.data as ekd

In [2]:
demo_ndarray = np.random.rand(10, 10) * 10.
demo_lats = np.arange(0, 91, 10)
demo_lons = np.arange(0, 91, 10)
# demo_ndarray

In [3]:
demo_da = xr.DataArray(
    demo_ndarray, name="temperature", dims={'latitude': demo_lats, 'longitude': demo_lons},
    attrs={'units': 'Celsius', "standard_name": "air_temperature"}
)
demo_ds = demo_da.to_dataset().assign_attrs({'purpose': 'Demonstration', 'source': 'EarthkitExamples'})

demo_ds

<xarray.Dataset> Size: 800B
Dimensions:      (latitude: 10, longitude: 10)
Dimensions without coordinates: latitude, longitude
Data variables:
    temperature  (latitude, longitude) float64 800B 2.842 9.335 ... 8.636 2.629
Attributes:
    purpose:  Demonstration
    source:   EarthkitExamples

In [4]:
ek_nd = ekd.from_object(demo_ndarray)
ek_nd.to_numpy()

array([[2.84166695, 9.33536102, 9.89642339, 2.6270859 , 8.48990799,
        7.26491482, 8.04717677, 0.88086053, 9.15001419, 9.11918713],
       [5.95637307, 0.99342671, 3.36424371, 4.12647013, 2.91330759,
        7.69611375, 0.86313991, 8.53523552, 7.74454754, 6.40762743],
       [2.0930653 , 9.07469986, 1.89753237, 8.76839945, 3.10963908,
        3.51962529, 7.44892355, 8.6962615 , 4.45429799, 3.70689399],
       [8.51173373, 9.71330098, 0.66754761, 9.35201523, 6.4197131 ,
        2.57457141, 9.06393373, 8.13740792, 6.29884532, 6.83748267],
       [1.92312384, 6.86896247, 1.31308448, 9.71517125, 6.10380899,
        8.69027922, 8.87550679, 9.54490803, 2.7651136 , 0.21012747],
       [6.33252307, 3.26345193, 0.5624723 , 8.13097045, 0.32727309,
        6.33340375, 6.43281711, 7.08033503, 7.93303826, 9.48912574],
       [8.96075398, 3.65606434, 5.13658636, 5.76677972, 9.48038899,
        9.59100093, 5.0829951 , 0.03339608, 7.45619778, 7.47936165],
       [0.98974923, 5.41995759, 7.8891442 , 8.63233891, 1.56722919,
        3.49653169, 5.22357   , 8.37571764, 3.72660086, 5.45440387],
       [2.97868482, 3.3038442 , 0.13717355, 8.71637329, 0.64545315,
        7.11183295, 4.84401703, 8.48792752, 8.89722967, 1.64760812],
       [7.70833552, 6.6173857 , 4.10199867, 3.17982421, 3.51557832,
        2.80264514, 4.99338519, 3.29805102, 8.63580364, 2.62885865]])

In [5]:
ek_da = ekd.from_object(demo_da)
ek_da.to_pandas()

                    temperature
latitude longitude
0        0             2.841667
         1             9.335361
         2             9.896423
         3             2.627086
         4             8.489908
...                         ...
9        5             2.802645
         6             4.993385
         7             3.298051
         8             8.635804
         9             2.628859

[100 rows x 1 columns]

In [6]:
ek_ds = ekd.from_object(demo_ds)
ek_ds.to_pandas()

                    temperature
latitude longitude
0        0             2.841667
         1             9.335361
         2             9.896423
         3             2.627086
         4             8.489908
...                         ...
9        5             2.802645
         6             4.993385
         7             3.298051
         8             8.635804
         9             2.628859

[100 rows x 1 columns]