In [1]:
import earthkit.data as ekd
import os

p = os.path.expanduser("~/git/earthkit-data/docs/examples/synop_10.bufr")

ds = ekd.from_source("file",p)

_from_source: src= <earthkit.data.readers.bufr.message_list.BUFRReader1 object at 0x1171774d0>

In [2]:
ds

In [3]:
ds.available_types

['pandas', 'featurelist']

In [4]:
ds.to_pandas(columns=["latitude", "longitude",
                     "heightOfStation","airTemperatureAt2M"])

   latitude  longitude  heightOfStation  airTemperatureAt2M
0    -10.75     179.50              3.0               300.4
1    -70.77      11.75              NaN               255.2
2     33.77       2.93            763.0               296.3
3     51.83     107.60            515.0               291.6
4     51.35     112.47            743.0               287.4
5     17.86     102.75            176.0               307.9
6      8.41     124.61            188.0               299.4
7    -26.50      29.98           1774.0               281.9
8    -29.60      31.12            105.0               299.8
9     -2.77    -171.72              2.0               302.1

In [5]:
ds.to_featurelist().ls()

,edition,type,subtype,c,mv,lv,subsets,compr,typicalDate,typicalTime,ident,lat,lon
0,3,0,1,98,13,1,1,0,20230602,120000,91648,-10.75,179.50
1,3,0,1,98,13,1,1,0,20230602,120000,89514,-70.77,11.75
2,3,0,1,98,13,1,1,0,20230602,120000,60545,33.77,2.93
3,3,0,1,98,13,1,1,0,20230602,120000,30823,51.83,107.60
4,3,0,1,98,13,1,1,0,20230602,120000,30846,51.35,112.47
5,3,0,1,98,13,1,1,0,20230602,120000,48352,17.86,102.75
6,3,0,1,98,13,1,1,0,20230602,120000,98747,8.41,124.61
7,3,0,1,98,13,1,1,0,20230602,120000,68267,-26.50,29.98
8,3,0,1,98,13,1,1,0,20230602,120000,68592,-29.60,31.12
9,3,0,1,98,13,1,1,0,20230602,120000,91701,-2.77,-171.72

In [7]:
for f in ds.to_featurelist():
    print(f)

BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)
BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)